#%RAML 1.0
title: employee-search-api
version: v1


/employeesearch:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              "Employee search successfull"